### ISSUE TITLE
Submodule page_content not available

### ISSUE THREAD

**Issue by kba** [ocr-d-modul-2-segmentierung/ocr4all-segmentation#1]
I cannot init the submodule at `git@gitlab2.informatik.uni-wuerzburg.de:alh75dg/page-content.git`

While that could be due to our firewall blocking outgoing ssh requests, I am not allowed to access it via browser either at https://gitlab2.informatik.uni-wuerzburg.de/alh75dg/page-content.git.

Can you move/mirror that repository to GitHub or allow external access?

**Comment by crater2150** [comment]
As I'm not project owner of the project in our Gitlab, I mirrored the repository on Github and changed the submodule URL accordingly.

In the long run, this submodule should probably be removed anyway. It removes page borders, which shouldn't be part of the job of this tool but an an earlier step. It's now also disabled by default (can be enabled with `--preprocess true`)
